import { ButtonIds } from "../enums/button-ids.js";
import { EggTypes } from "../enums/egg-types.js";

export const ANSWERS = new Map([
    [ButtonIds.Q1A1, EggTypes.Scrambled],
    [ButtonIds.Q1A2, EggTypes.Fried],
    [ButtonIds.Q1A3, EggTypes.Deviled],
    [ButtonIds.Q1A4, EggTypes.Dinosaur],
    [ButtonIds.Q2A1, EggTypes.Scrambled],
    [ButtonIds.Q2A2, EggTypes.Fried],
    [ButtonIds.Q2A3, EggTypes.Deviled],
    [ButtonIds.Q2A4, EggTypes.Dinosaur],
    [ButtonIds.Q3A1, EggTypes.Scrambled],
    [ButtonIds.Q3A2, EggTypes.Fried],
    [ButtonIds.Q3A3, EggTypes.Deviled],
    [ButtonIds.Q3A4, EggTypes.Dinosaur],
    [ButtonIds.Q4A1, EggTypes.Scrambled],
    [ButtonIds.Q4A2, EggTypes.Fried],
    [ButtonIds.Q4A3, EggTypes.Deviled],
    [ButtonIds.Q4A4, EggTypes.Dinosaur],
    [ButtonIds.Q5A1, EggTypes.Scrambled],
    [ButtonIds.Q5A2, EggTypes.Fried],
    [ButtonIds.Q5A3, EggTypes.Deviled],
    [ButtonIds.Q5A4, EggTypes.Dinosaur],
    [ButtonIds.Q6A1, EggTypes.Scrambled],
    [ButtonIds.Q6A2, EggTypes.Fried],
    [ButtonIds.Q6A3, EggTypes.Deviled],
    [ButtonIds.Q6A4, EggTypes.Dinosaur],
    [ButtonIds.Q7A1, EggTypes.Scrambled],
    [ButtonIds.Q7A2, EggTypes.Fried],
    [ButtonIds.Q7A3, EggTypes.Deviled],
    [ButtonIds.Q7A4, EggTypes.Dinosaur],
    [ButtonIds.Q8A1, EggTypes.Scrambled],
    [ButtonIds.Q8A2, EggTypes.Fried],
    [ButtonIds.Q8A3, EggTypes.Deviled],
    [ButtonIds.Q8A4, EggTypes.Dinosaur],
    [ButtonIds.Q9A1, EggTypes.Scrambled],
    [ButtonIds.Q9A2, EggTypes.Fried],
    [ButtonIds.Q9A3, EggTypes.Deviled],
    [ButtonIds.Q9A4, EggTypes.Dinosaur]
]);
